version: "3.8"
services:
  lbg-car-front:
    image: ctm2000/lbg-car-front:latest
    ports:
    - target: 80
      published: 80
    depends_on:
    - lbg-car-back
    networks:
    - car-net
  lbg-car-back:
    image: ctm2000/lbg-car-back:latest
    ports:
    - target: 8000
      published: 8000
    depends_on:
    - mysql
    restart: on-failure
    networks:
    - car-net
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cardb_jwt
    networks:
    - car-net
    volumes:
    - type: volume
      source: cardb-vol
      target: /var/lib/mysql
networks:
  car-net:
volumes:
  cardb-vol:
